name: Build and Push

on:
  push:
    branches:
      - main
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerhubUser }}
        password: ${{ secrets.DockerhubPass }}
    - name: Docker Build
      if: contains(github.ref, 'main')
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Hookerr/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: |
          joene/hookerr:latest
          joene/hookerr:${{ steps.vars.outputs.sha_short }}
    - name: Docker Build
      if: contains(github.ref, 'devel')
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Hookerr/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: |
        joene/hookerr:devel
        joene/hookerr:${{ steps.vars.outputs.sha_short }}