name: Build and Push

on:
  push:
    branches:
      - main
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Build
      if: contains(github.ref, 'main')
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{ secrets.DockerhubUser }}
        password: ${{ secrets.DockerhubPass }}
        repository: ${{ secrets.DockerhubRepo }}
        tags: latest
        tag_with_ref: false
        tag_with_sha: true
    - name: Docker Build
      if: contains(github.ref, 'devel')
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{ secrets.DockerhubUser }}
        password: ${{ secrets.DockerhubPass }}
        repository: ${{ secrets.DockerhubRepo }}
        tags: devel
        tag_with_ref: false
        tag_with_sha: true
